delete from LIBELLE
delete from LIEN_ROLE_RESSOURCE; 
delete from LIEN_UTILISATEUR_ROLE;
delete from RESSOURCE;
delete from ROLE;
delete from UTILISATEUR;
delete from FACTURE;
delete from CONSOMMATION;
delete from OPTION_RESERVEE;
delete from OPTION_RESERVATION;
delete from PAIEMENT;
delete from RESERVATION;
delete from CHAMBRE;
delete from PRODUIT;
delete from FORMULE;
delete from MOYEN_DE_PAIEMENT;