delete from LIBELLE
delete from LIEN_ROLE_RESSOURCE; 
delete from LIEN_UTILISATEUR_ROLE;
delete from RESSOURCE;
delete from ROLE;
delete from UTILISATEUR;
delete from DEMANDE;
delete from DOSSIER;
delete from CLIENT;
delete from ADRESSE;
delete from consommation;
delete from reservation;
delete from chambre;
delete from produit;