service: 'appliblanche-rest'
runtime: java
api_version: '1.0'
env: flex
threadsafe: true
inbound_services:
  - warmup
handlers:
  - url: '/.*'
    script: unused
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 2
  memory_gb: 2.3
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
